name: Configuring Scanner

on:
  workflow_dispatch:

jobs:

  sonar-qube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH into EC2 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            sudo -i
            

            # Add the specified configurations to sonar-scanner.properties
            echo "sonar.projectKey=aws_Rentte" | sudo tee -a /opt/sonar-scanner-7.0.2.4839-linux-x64/conf/sonar-scanner.properties
            echo "sonar.sources=lambda,lib,bin" | sudo tee -a /opt/sonar-scanner-7.0.2.4839-linux-x64/conf/sonar-scanner.properties
            echo "sonar.language=js" | sudo tee -a /opt/sonar-scanner-7.0.2.4839-linux-x64/conf/sonar-scanner.properties
            echo "sonar.exclusions=node_modules/**,coverage/**" | sudo tee -a /opt/sonar-scanner-7.0.2.4839-linux-x64/conf/sonar-scanner.properties
            echo "sonar.javascript.lcov.reportPaths=coverage/lcov.info" | sudo tee -a /opt/sonar-scanner-7.0.2.4839-linux-x64/conf/sonar-scanner.properties
            echo "sonar.eslint.reportPaths=eslint-report.json" | sudo tee -a /opt/sonar-scanner-7.0.2.4839-linux-x64/conf/sonar-scanner.properties
            echo "sonar.qualitygate.wait=true" | sudo tee -a /opt/sonar-scanner-7.0.2.4839-linux-x64/conf/sonar-scanner.properties
            echo "sonar.host.url=http://13.232.185.209:9000" | sudo tee -a /opt/sonar-scanner-7.0.2.4839-linux-x64/conf/sonar-scanner.properties
            echo "sonar.token=sqp_c4b4396c4d265a8d68e47db9e999265e74ba5bcf" | sudo tee -a /opt/sonar-scanner-7.0.2.4839-linux-x64/conf/sonar-scanner.properties

            cd /opt/Rentte-backend/Rentte/Rentte-aws-lambda

            # Install Node.js and NPM
            sudo yum install -y nodejs npm

            # Install project dependencies
            sudo npm install

            # Run tests with coverage
            sudo npm test -- --coverage

            # Install ESLint and initialize
            sudo npm install --save-dev eslint
            sudo npx eslint --init
            sudo npx eslint .
            
            sudo -i
            cd /opt/Rentte-backend/Rentte/Rentte-aws-lambda
            sonar-scanner
            
            
